# Load profiles for machines from profiles folder
# Create Template Machine (Template -> Custodian)
# 

- name: Initialize an EC2 Cluster for data.connor.fun
  hosts: local
  
  vars_files:
    - keys.yaml
    - machines.yaml

  tasks:

    # - name: This is a test machine
    #   ec2:
    #     aws_access_key: "{{aws_auth.access}}"
    #     aws_secret_key: "{{aws_auth.secret}}"
    #     key_name: connor.fun
    #     instance_type: t2.micro
    #     image: ami-e2e9729a
    #     region: us-west-2
    
    - name: Create necessary security groups for cluster
      ec2_group:
        name: connor.fun-SSH
        description: SSH Group for connor.fun instances
        region: us-west-2
        aws_access_key: "{{aws_auth.access}}"
        aws_secret_key: "{{aws_auth.secret}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        tags:
          "Name": connor.fun-SSH
          "Team Name": connor.fun
      register: response
    
    - debug:
        msg: "{{response}}"