- name: Prepare AWS environment for connor.fun storm network
  hosts: local
  
  vars_files:
    - vars/keys.yaml
    - vars/security_groups.yaml
    - vars/machines.yaml
    - vars/config.yaml

  tasks:

    - name: Create Worker Machines for Storm
      ec2:
        aws_access_key: "{{ aws_auth.access }}"
        aws_secret_key: "{{ aws_auth.secret }}"
        key_name: "{{ ssh_key_name + '.pem' }}"
        group: "{{ Worker.group }}"
        instance_type: "{{ Worker.instance_type }}"
        image: "{{ Custodian_AMI }}"
        region: "{{ region }}"
        count: "{{ Worker.count }}"
        instance_tags: "{{ Worker.tags }}"
      register: Worker_Response
    
    - name: Make log of security group creation
      copy: 
        content: "{{ Worker_Response | to_nice_json }}"
        dest: logs/Worker_generation.log

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item['public_ip'] }}"
        port: 22
        state: started
      with_items: "{{Worker_Response['instances']}}"
    
    - name: Copy supervisors.conf to machine