- name: Create the connor.fun cluster
  hosts: local
  gather_facts: no
  
  vars_files:
    - vars/keys.yaml
    - vars/security_groups.yaml
    - vars/machines.yaml
    - vars/config.yaml

  tasks:

    - name: test out ec2_ami_facts
      ec2_ami_facts:
        aws_access_key: "{{ aws_auth.access }}"
        aws_secret_key: "{{ aws_auth.secret }}"
        describe_image_attributes: yes
        region: "{{ region }}"
        filters:
          name: connor.fun-AMI
      register: AMI-Search
    
    - debug:
        msg: "{{ ec2_out }}"
      when: ec2_out["images"] != []