- name: This is my playground for testing, it usually holds whatever I've been testing most recently
  hosts: all
  
  vars_files:
    - vars/keys.yaml
    - vars/security_groups.yaml
    - vars/machines.yaml
    - vars/config.yaml

  vars:
    test_var: "Hello World!"

  tasks:

    - template:
        src: test.conf.j2
        dest: test.conf
