- name: This is my playground for testing, it usually holds whatever I've been testing most recently
  hosts: local
  gather_facts: no
  
  vars_files:
    - vars/keys.yaml
    - vars/security_groups.yaml
    - vars/machines.yaml
    - vars/config.yaml

  vars:

  tasks:
