- name: Prepare AWS environment for connor.fun storm network
  hosts: local
  
  vars_files:
    - vars/keys.yaml
    - vars/security_groups.yaml
    - vars/machines.yaml
    - vars/config.yaml

  tasks:

    # ==== Begin Rule and Key Generation ====

    - name: Create necessary security group for cluster
      ec2_group:
        aws_access_key: "{{ aws_auth.access }}"
        aws_secret_key: "{{ aws_auth.secret }}"
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        region: "{{ region }}"
        rules: "{{ item.rules }}"
        rules_egress: "{{item.rules_egress}}"
        tags: "{{ item.tags }}"
      loop: "{{ security_groups }}"
      register: Security_Response

    - name: Make log of security group creation
      copy: 
        content: "{{ Security_Response | to_nice_yaml }}"
        dest: logs/Security_Group_generation.yaml

    - name: Create SSH key for machines
      ec2_key:
        aws_access_key: "{{ aws_auth.access }}"
        aws_secret_key: "{{ aws_auth.secret }}"
        name: "{{ ssh_key_name }}"
        region: "{{ region }}"
      register: SSHKey_Response

    - name: Make log of SSHkey generation
      copy: 
        content: "{{ SSHKey_Response | to_nice_yaml }}"
        dest: logs/SSHKey_generation.yaml

    - name: Save .pem file to local directory (./)
      copy: 
        content: "{{ SSHKey_Response['key']['private_key'] }}"
        dest: "{{ ssh_key_name + '.pem' }}"
        mode: 0400

    - name: Template configs/environment
      template:
        src: templates/environment.j2
        dest: configs/environment

    - name: Template configs/storm-env.sh
      template:
        src: templates/environment.j2
        dest: configs/storm-env.sh
